### ISSUE TITLE
Large query downloads fail (downloads page)

### ISSUE THREAD

**Issue by beangoben** [metabolomics-us/mona#49]
Attempting to download a query from https://mona.fiehnlab.ucdavis.edu/downloads fails.

For example If I try to download 
`[GC-MS Spectra](https://mona.fiehnlab.ucdavis.edu/spectra/browse?query=tags.text%3D%3D%22GC-MS%22)`
on a chrome browser in any format will result in a 'Failed - No File' message.

Using curl will result in only files with 10k entries but not all, it is not possible to offset the queries so you are stuck with the same 10k entries.

**Comment by NolanGuzman97** [comment]
Apologies for this, working to get the downloads regenerated and they are taking quit a bit of time. Looking into ways to speed up this process

**Comment by NolanGuzman97** [comment]
@beangoben Deployment of new code will be performed at 12PM today. Slowing down file generation to once a week and upping pick size from 25 to 250. Should help create the files faster and take load off the server until further optimizations can be made following spring boot 2 upgrades. Thank you for reporting!
