### ISSUE TITLE
Similarity Search (Server error 500)

### ISSUE THREAD

**Issue by gdrocks15** [metabolomics-us/mona#59]
Tested in both Google Chrome (Version 103.0.5060.134 (Official Build) (64-bit)), and Microsoft Edge  (Version 103.0.1264.62 (Official build) (64-bit)) after clearing all browser data for both on Windows 10. 

When trying to use "Search Spectra -> Similarity Search", able to enter and load the mass spectrum, and verify the mass spectrum. Upon selecting "Search for Similar Spectra" receive page stating "No results found!" and an error box stating:

```
Unexpected Error Occurred During Search
If this error continues to occur, please report the following error on YouTrack [object Object]
```

When checking console, after "Executing similarity search..." receiving an error from

```
/rest/similarity/search:1
       Failed to load resource: the server responded with a status of 500 (Server Error)
```
following that path shown error page:
```
Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Wed Jul 20 16:52:07 UTC 2022
There was an unexpected error (type=Internal Server Error, status=500).
GENERAL
```

**Comment by NolanGuzman97** [comment]
Service was down during this time, confirmed that service is currently operational.
