### ISSUE TITLE
Move LipidBlast to in silico spectra?

### ISSUE THREAD

**Issue by Adafede** [metabolomics-us/mona#65]
Hi,

At <https://mona.fiehnlab.ucdavis.edu/downloads>, it looks like LipidBlast is included in the "experimental spectra", probably because of the "!= in silico" not discarding them.

I think this shouldn't be the case, right?

Best,

**Comment by NolanGuzman97** [comment]
Hi there, yes you are correct the LipidBlast 2022 library should be tagged with In-Silico so that it is part of the In-Silico download and not experimental. We are working on a huge refactor of our backend and will be correcting LipidBlast 2022 when that new backend is deployed. Thank you!

**Comment by NolanGuzman97** [comment]
Code is being deployed today to fix this issue. Thanks for reporting it! @Adafede
