### ISSUE TITLE
Similar Spectra search error

### ISSUE THREAD

**Issue by gdrocks15** [metabolomics-us/mona#9]
When attempting to search for similar spectra after providing peak list, receive error stating "Unexpected Error Occurred During Search - If this error continues to occur, please report the following error on YouTrack [object Object]"

Unable to signup or login as guest to post error on YouTrack.

**Comment by gdrocks15** [comment]
1. Goto https://mona.fiehnlab.ucdavis.edu/spectra/search
2. Goto "Similarity Search"
3. In the "Paste a Mass Spectrum:" text box, paste list of ions and abundances. Per row, have one ion and one abundance pair separated by a single space.
To get this list, I took the tabulated data from a spectrum in Agilent Chemstation and pasted into Excel. Then I made a formula to concatenate the ion and abundance as integers with a single space. Example formula: '=concat(round(A5,0)," ",round(B5,0))' -> 30 428 (See attached text file for full list of values)
4. Click 'Load Spectrum'
5. Confirm spectrum loaded properly and click 'Search for Similar Spectra'
6. Taken to https://mona.fiehnlab.ucdavis.edu/spectra/browse?size=10 and error is shown. In some cases, taken to that web address but not shown the error message.


![image](https://user-images.githubusercontent.com/36310834/138324191-9553ddb0-7f22-40b9-8eb2-ed28bb41cbfb.png)
[Sample_MSData.txt](https://github.com/metabolomics-us/mona/files/7391587/Sample_MSData.txt)


Error occurred with both Chrome and Edge:
Chrome: Version 94.0.4606.81 (Official Build) (64-bit)
Microsoft Edge: Version 94.0.992.50 (Official build) (64-bit)

**Comment by gdrocks15** [comment]
Hi, still having issues and unable to use similarity search. I cleared browser data and tried with both Chrome and Microsoft Edge. 

Once I see preview of spectrum and hit "Search for Similar Spectra" I am taken to the homepage/spectra Browse Spectra page.
https://mona.fiehnlab.ucdavis.edu/spectra/browse?size=10

Same issue as before however no longer shown an error message.

**Comment by NolanGuzman97** [comment]
> Hi, still having issues and unable to use similarity search. I cleared browser data and tried with both Chrome and Microsoft Edge.
> 
> Once I see preview of spectrum and hit "Search for Similar Spectra" I am taken to the homepage/spectra Browse Spectra page. https://mona.fiehnlab.ucdavis.edu/spectra/browse?size=10
> 
> Same issue as before however no longer shown an error message.

The changes have not gone to the production site, the ticket will have a "Closed" status when the issue has been completely resolved, we are just awaiting testing approvals for changes that will go alongside it. Thanks for your patience.

**Comment by NolanGuzman97** [comment]
Issue closed, fix will be deployed today at 5 PM.
